---
title: "Sensitivity_analysis_almond"
author: "Steven Cognac"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(patchwork)
library(pse)
```

```{r}
# for formal sensitivity analysis it is useful to describe output in
# several summary statistics - how about mean, max and min yield
source(here("R/crop_water_use.R"))
```

```{r}
# You are estimating the atmospheric conductance for a forest that is 10 m high (the accuracy of that measurement is +/- 0.5 m ) Windspeeds v in this region are normally distributed with a mean of 250 cm/s with a standard deviation of 30 cm/s
crop_water_use(v_m=250, h=1000)

```


# Part A. Use LHS to generate parameter values for the 4 parameters
```{r}
# consider 4 parameters
factors = c("v_m", "k_d", "k_0", "h")

# calculate number of sets
nsets = 100

# choose distribution of parameters
q = c("qnorm", "qnorm", "qnorm", "qunif")
q.arg = list(list(mean=250, sd=30), list(mean=0.7, sd=0.007), list(mean=0.1, sd=0.001), list(min=950, max=1050))

# generate samples for LHS
sens_crop_water = LHS(NULL, factors, nsets, q, q.arg)
sens_params = get.data(sens_crop_water)
head(sens_params)
```
# Part B. Run atmospheric conductance model for these parameters and return aerodynamic conductances
```{r}
# lets now run our model for all of the parameters generated by LHS
crop_water = sens_params %>% 
  pmap(crop_water_use, z_m=200) %>%
  bind_rows() # turn results in to a dataframe for easy display/analysis

head(crop_water)
```

```{r}
# tell is what links output to original LHS object
sens_conductance <- pse::tell(sens_crop_water, t(as.matrix(crop_water)),
                        res.names=c("conductance"))
```

# Part C. Plot conductance estimates in a way that accounts for parameter uncertainty
```{r}
hist <- ggplot(crop_water, aes(conductance)) +
  geom_histogram() +
  labs(subtitle = "Histogram",
       x = "(cm/s)")
box <- ggplot(crop_water, aes(conductance)) +
  geom_boxplot() +
  labs(subtitle = "Boxplot",
       x = "(cm/s)") +
  coord_flip()

(hist + box) + plot_annotation(title = "LHS Sensitivity Analysis of Atmospheric Conductance")
```

# Part D. Plot conductance estimates against each of your parameters
```{r}
# now we use built in LHS functions to analyze parameter sensitivity
pse::plotscatter(sens_conductance, col="blue", cex=5)
```


# Part E. Est. PRCC
```{r}
# partial rankk correlation coefficients
sens_conductance$prcc
```

